name: Provision Infrastructure for wordpress
on:
    push:
      branches:
        - test
    #     paths:
    #       - ./environments/dev/*
    #       - ./environments/prod/*  
    # pull_request:
    #     paths:
    #       - ./environments/dev/*
    #       - ./environments/prod/*
    workflow_dispatch:
        

jobs:
  dev:
    name: Terraform Deploy to Development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev/  # Set the working directory for dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  # Adjust the Terraform version if necessary

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            echo "AWS credentials are configured"

      # - name: Wordpress_key
      #   env:
      #     WORDPRESS_KEY: ${{ secrets.WORDPRESS_KEY }}
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "Length of WORDPRESS_KEY: ${#WORDPRESS_KEY}"
          
      #     echo "$WORDPRESS_KEY" | base64 --decode > ~/.ssh/id_rsa || {
      #       echo "Error decoding WORDPRESS_KEY"; exit 1;
      #     }
    
      #     chmod 600 ~/.ssh/id_rsa
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform fmt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform fmt

      - name: Terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform validate

      - name: Set up SSH Key for Terraform
        env:
          WORDPRESS_SSH_KEY: ${{ secrets.WORDPRESS_SSH_KEY }}
        run: |
          # Decode and store the private key in a temporary file
          mkdir -p ~/.ssh
          echo "$WORDPRESS_KEY" > ~/.ssh/wordpress.pem
          chmod 600 ~/.ssh/wordpress.pem

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          WORDPRESS_KEY: ${{ secrets.WORDPRESS_KEY }}
        run: terraform plan
      
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          WORDPRESS_KEY: ${{ secrets.WORDPRESS_KEY }}
        run: terraform apply -auto-approve -var="WORDPRESS_KEY=$(cat ~/.ssh/wordpress.pem)"

      

        
  