name: Provision Infrastructure for wordpress
on:
    push:
      branches:
        - test
    #     paths:
    #       - ./environments/dev/*
    #       - ./environments/prod/*  
    # pull_request:
    #     paths:
    #       - ./environments/dev/*
    #       - ./environments/prod/*
    workflow_dispatch:
        

jobs:
  dev:
    name: Terraform Deploy to Development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev/  # Set the working directory for dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  # Adjust the Terraform version if necessary

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            echo "AWS credentials are configured"

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform fmt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform fmt

      - name: Terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform validate

      - name: Set up SSH Key for Terraform
        env:
          WORDPRESS_KEY: ${{ secrets.WORDPRESS_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$WORDPRESS_KEY" | tr -d '\r' > ~/.ssh/wordpress.pem
          chmod 600 ~/.ssh/wordpress.pem
          ls -la ~/.ssh

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -var="WORDPRESS_KEY=$(cat ~/.ssh/wordpress.pem)"

      
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -var="WORDPRESS_KEY=$(cat ~/.ssh/wordpress.pem)"
     
      - name: Terraform destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -manual-approve -var="WORDPRESS_KEY=$(cat ~/.ssh/wordpress.pem)"

  prod:
    name: Terraform Deploy to Productions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/prod/  # Set the working directory for dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  # Adjust the Terraform version if necessary

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            echo "AWS credentials are configured"

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform fmt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform fmt

      - name: Terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform validate

      - name: Set up SSH Key for Terraform
        env:
          WORDPRESS_KEY: ${{ secrets.WORDPRESS_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$WORDPRESS_KEY" | tr -d '\r' > ~/.ssh/wordpress.pem
          chmod 600 ~/.ssh/wordpress.pem
          ls -la ~/.ssh

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -var="WORDPRESS_KEY=$(cat ~/.ssh/wordpress.pem)"

      
      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -var="WORDPRESS_KEY=$(cat ~/.ssh/wordpress.pem)"   

        
  